### ISSUE TITLE
Gradle build failed, 

### ISSUE THREAD

**Issue by teruun** [succlz123/DoubanBookLog#1]
显示错误信息如下：

Error:A problem occurred configuring root project 'DoubanBookLog-master'.

> Could not resolve all dependencies for configuration ':classpath'.
> Could not resolve com.android.tools.build:gradle:1.1.1.
>      Required by:
>          :DoubanBookLog-master:unspecified
>       > Could not GET 'http://192.168.1.104:8081/nexus/content/groups/public/com/android/tools/build/gradle/1.1.1/gradle-1.1.1.pom'.
>          > Connection to http://192.168.1.104:8081 refused

请问大侠有没有什么方法可以解决这个问题，我用了代理也没能搞定。。。  有没有其他的什么办法呢。很想学习一下这个项目。
谢谢！

**Comment by succlz123** [comment]
```
buildscript {
  repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.1'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
```

因为我用了本地仓库 你把他改成jcenter()就行了
